### ISSUE TITLE
Successfully run the psr --help command in the skeleton GitHub workflow

### ISSUE THREAD

**Issue by dwinchell** [ploigos-github-demo/java-app#2]
Currently, the workflow just runs echo commands. We want it to run a psr command to prove that we have the psr present and are able to execute it successfully.

This has two parts:
1. Install the PSR step runner in the pipeline
2. Execute the PSR step runner in the pipeline

Assumptions:
* We will use GitHub self-hosted runner to run the actions. We won't use a self-hosted GitHub Runner.
* We will install PSR in the "Setup Workflow Step Runner" workflow here: https://github.com/ploigos/ploigos-github-workflows/blob/main/.github/workflows/setup-workflow-step-runner.yaml
* We *may* have to use the "python" GitHub action to install python - https://github.com/marketplace/actions/setup-python
* We will reuse some of the code from the Jenkins or Tekton implementations, here: https://github.com/ploigos/ploigos-jenkins-library/blob/main/vars/ploigosWorkflowMinimal.groovy#L391
* We will install PSR from source, i.e. set stepRunnerUpdateLibrary to "true" and set stepRunnerLibSourceUrl to "git+https://gitea.internal.example.xyz/tools/ploigos-step-runner.git@main" (or simplify the conditional logic so we don't have those parameters)
* We will execute the PSR step runner in the Generate Metadata step, here: https://github.com/ploigos/ploigos-github-workflows/blob/main/.github/workflows/ci-generate-metadata.yaml#L37
* The Setup step will happen before the GenerateMetadata step. Otherwise GenerateMetadata will break.
* We will *probably* have to run the same steps in the same Job ... because (Dillon thinks) two Jobs do not share state, i.e. if you install a pythong program in one Job it won't show up in the other Job ... but there may be a better way to do it that Dillon doesn't know about.

Out of Scope (future stories):
* Creating a custom Action for the PSR. We can just include the call in the script below the echo statement.
* Doing anything useful with the psr. Running it with a --help flag is fine.
* Setting up a self-hosted GitHub Runner for OpenShift.

**Comment by dwinchell** [comment]
@gfulton-redhat @aarongreen85 I suggest that we work on this story next, unless there is something that should take precedence that I am not aware of.

**Comment by gfulton-redhat** [comment]
@dwinchell can we discuss the approach in the morning working session? I was able to run `psr --help` using a custom action the pulled in the ploigos-base container.
